apiVersion: v1
kind: ConfigMap
metadata:
  name: trade-statistics-webapp-configmap
  namespace: learning-ks
data:

  application.properties: |
    spring.application.name=trade-statistics-webapp
    
    schema.registry.url=http://schema-registry:8081
    
    spring.kafka.bootstrap-servers=schema-registry-kafka-controller-headless:9092
    
    spring.kafka.properties.schema.registry.url=${schema.registry.url}
    spring.kafka.properties.client.dns.lookup=use_all_dns_ips
    
    spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.IntegerSerializer
    spring.kafka.producer.value-serializer=io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
    
    server.port=8080
    
    trade-statistics.base-url=http://trade-statistics-aggregator-headless-svc:8080