apiVersion: v1
kind: ConfigMap
metadata:
  name: trade-statistics-aggregator-configmap
  namespace: learning-ks
data:

  application.properties: |
    spring.application.name=trade-statistics-aggregator
    
    spring.docker.compose.enabled=false
    
    server.port=8080
    
    schema.registry.url=http://schema-registry:8081
    
    spring.kafka.streams.bootstrap-servers=schema-registry-kafka-controller-headless:9092
    spring.kafka.streams.properties.default.deserialization.exception.handler=org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
    spring.kafka.streams.properties.schema.registry.url=${schema.registry.url}
    spring.kafka.streams.properties.application.server=${HOSTNAME}:${server.port}
    spring.kafka.streams.properties.client.dns.lookup=use_all_dns_ips
    spring.kafka.admin.auto-create=true
    spring.kafka.bootstrap-servers=schema-registry-kafka-controller-headless:9092
    
    spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.IntegerSerializer
    spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
